# Default values for flask-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: chnpmy/kubeflask
  tag: 0.1.0
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  internalPort: 5000
  externalPort: 5000